### ISSUE TITLE
IKucoinSocketClient - Connection is lost without restore

### ISSUE THREAD

**Issue by keyvanme** [JKorf/Kucoin.Net#147]
Hi . I read issue #140 and updated kucoin.net to 4.0.8 .
i ran the program and after 2 days , i got same error again and connections could not restore.
Property AutoReconnect is set to true.

log: 
  Socket 1 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.  
at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options) at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

**Comment by JKorf** [comment]
That log entry doesn't mean that it didn't reconnect, just that that specific reconnect attempt failed. It'll try again after that. Are you sure it didn't reconnect eventually?

**Comment by keyvanme** [comment]
2022/07/06 16:30:48:839 | Debug | Kucoin     | Socket 89 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:48:862 | Debug | Kucoin     | Socket 91 resetting
2022/07/06 16:30:48:863 | Debug | Kucoin     | Socket 91 connecting
2022/07/06 16:30:48:863 | Debug | Kucoin     | Socket 93 resetting
2022/07/06 16:30:48:862 | Debug | Kucoin     | Socket 31 resetting
2022/07/06 16:30:48:865 | Debug | Kucoin     | Socket 93 connecting
2022/07/06 16:30:48:865 | Debug | Kucoin     | Socket 31 connecting
2022/07/06 16:30:48:909 | Debug | Kucoin     | Socket 115 resetting
2022/07/06 16:30:48:909 | Debug | Kucoin     | Socket 115 connecting
2022/07/06 16:30:48:909 | Debug | Kucoin     | Socket 94 resetting
2022/07/06 16:30:48:911 | Debug | Kucoin     | Socket 94 connecting
2022/07/06 16:30:48:909 | Debug | Kucoin     | Socket 9 resetting
2022/07/06 16:30:48:912 | Debug | Kucoin     | Socket 9 connecting
2022/07/06 16:30:48:940 | Debug | Kucoin     | Socket 33 resetting
2022/07/06 16:30:48:940 | Debug | Kucoin     | Socket 10 resetting
2022/07/06 16:30:48:940 | Debug | Kucoin     | Socket 114 resetting
2022/07/06 16:30:48:940 | Debug | Kucoin     | Socket 72 resetting
2022/07/06 16:30:48:943 | Debug | Kucoin     | Socket 72 connecting
2022/07/06 16:30:48:941 | Debug | Kucoin     | Socket 30 resetting
2022/07/06 16:30:48:943 | Debug | Kucoin     | Socket 30 connecting
2022/07/06 16:30:48:941 | Debug | Kucoin     | Socket 33 connecting
2022/07/06 16:30:48:943 | Debug | Kucoin     | Socket 10 connecting
2022/07/06 16:30:48:943 | Debug | Kucoin     | Socket 114 connecting
2022/07/06 16:30:48:941 | Debug | Kucoin     | Socket 49 resetting
2022/07/06 16:30:48:945 | Debug | Kucoin     | Socket 49 connecting
2022/07/06 16:30:48:941 | Debug | Kucoin     | Socket 109 resetting
2022/07/06 16:30:48:946 | Debug | Kucoin     | Socket 109 connecting
2022/07/06 16:30:48:972 | Debug | Kucoin     | Socket 53 resetting
2022/07/06 16:30:48:972 | Debug | Kucoin     | Socket 69 resetting
2022/07/06 16:30:48:972 | Debug | Kucoin     | Socket 53 connecting
2022/07/06 16:30:48:974 | Debug | Kucoin     | Socket 69 connecting
2022/07/06 16:30:48:987 | Debug | Kucoin     | Socket 12 resetting
2022/07/06 16:30:48:989 | Debug | Kucoin     | Socket 12 connecting
2022/07/06 16:30:49:034 | Debug | Kucoin     | Socket 110 resetting
2022/07/06 16:30:49:034 | Debug | Kucoin     | Socket 110 connecting
2022/07/06 16:30:49:065 | Debug | Kucoin     | Socket 111 resetting
2022/07/06 16:30:49:065 | Debug | Kucoin     | Socket 111 connecting
2022/07/06 16:30:49:096 | Debug | Kucoin     | Socket 75 resetting
2022/07/06 16:30:49:096 | Debug | Kucoin     | Socket 75 connecting
2022/07/06 16:30:49:096 | Debug | Kucoin     | Socket 32 resetting
2022/07/06 16:30:49:097 | Debug | Kucoin     | Socket 32 connecting
2022/07/06 16:30:49:113 | Debug | Kucoin     | Socket 54 resetting
2022/07/06 16:30:49:113 | Debug | Kucoin     | Socket 48 resetting
2022/07/06 16:30:49:113 | Debug | Kucoin     | Socket 95 resetting
2022/07/06 16:30:49:114 | Debug | Kucoin     | Socket 48 connecting
2022/07/06 16:30:49:114 | Debug | Kucoin     | Socket 54 connecting
2022/07/06 16:30:49:114 | Debug | Kucoin     | Socket 95 connecting
2022/07/06 16:30:49:113 | Debug | Kucoin     | Socket 113 resetting
2022/07/06 16:30:49:115 | Debug | Kucoin     | Socket 113 connecting
2022/07/06 16:30:49:143 | Debug | Kucoin     | Socket 50 resetting
2022/07/06 16:30:49:144 | Debug | Kucoin     | Socket 50 connecting
2022/07/06 16:30:49:190 | Debug | Kucoin     | Socket 11 resetting
2022/07/06 16:30:49:190 | Debug | Kucoin     | Socket 73 resetting
2022/07/06 16:30:49:191 | Debug | Kucoin     | Socket 92 resetting
2022/07/06 16:30:49:192 | Debug | Kucoin     | Socket 92 connecting
2022/07/06 16:30:49:192 | Debug | Kucoin     | Socket 73 connecting
2022/07/06 16:30:49:191 | Debug | Kucoin     | Socket 11 connecting
2022/07/06 16:30:49:300 | Debug | Kucoin     | Socket 112 resetting
2022/07/06 16:30:49:300 | Debug | Kucoin     | Socket 28 resetting
2022/07/06 16:30:49:300 | Debug | Kucoin     | Socket 112 connecting
2022/07/06 16:30:49:302 | Debug | Kucoin     | Socket 28 connecting
2022/07/06 16:30:49:456 | Debug | Kucoin     | Socket 34 resetting
2022/07/06 16:30:49:456 | Debug | Kucoin     | Socket 34 connecting
2022/07/06 16:30:49:487 | Debug | Kucoin     | Socket 29 resetting
2022/07/06 16:30:49:487 | Debug | Kucoin     | Socket 70 resetting
2022/07/06 16:30:49:487 | Debug | Kucoin     | Socket 29 connecting
2022/07/06 16:30:49:488 | Debug | Kucoin     | Socket 70 connecting
2022/07/06 16:30:49:541 | Debug | Kucoin     | Socket 6 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:543 | Debug | Kucoin     | Socket 6 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:593 | Debug | Kucoin     | Socket 51 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:595 | Debug | Kucoin     | Socket 51 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:636 | Debug | Kucoin     | Socket 7 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:638 | Debug | Kucoin     | Socket 7 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:699 | Debug | Kucoin     | Socket 74 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:702 | Debug | Kucoin     | Socket 74 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:700 | Debug | Kucoin     | Socket 27 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:699 | Debug | Kucoin     | Socket 71 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:702 | Debug | Kucoin     | Socket 52 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:702 | Debug | Kucoin     | Socket 27 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:703 | Debug | Kucoin     | Socket 71 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:703 | Debug | Kucoin     | Socket 52 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:706 | Debug | Kucoin     | Socket 96 resetting
2022/07/06 16:30:49:706 | Debug | Kucoin     | Socket 96 connecting
2022/07/06 16:30:49:709 | Debug | Kucoin     | Socket 90 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:709 | Debug | Kucoin     | Socket 90 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:729 | Debug | Kucoin     | Socket 8 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:730 | Debug | Kucoin     | Socket 8 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:774 | Debug | Kucoin     | Socket 91 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:775 | Debug | Kucoin     | Socket 91 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:790 | Debug | Kucoin     | Socket 93 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:791 | Debug | Kucoin     | Socket 93 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:799 | Debug | Kucoin     | Socket 31 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:802 | Debug | Kucoin     | Socket 31 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:825 | Debug | Kucoin     | Socket 9 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:825 | Debug | Kucoin     | Socket 9 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:828 | Debug | Kucoin     | Socket 94 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:828 | Debug | Kucoin     | Socket 94 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:834 | Debug | Kucoin     | Socket 115 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:839 | Debug | Kucoin     | Socket 115 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:856 | Debug | Kucoin     | Socket 72 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:857 | Debug | Kucoin     | Socket 72 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:857 | Debug | Kucoin     | Socket 114 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:857 | Debug | Kucoin     | Socket 114 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:861 | Debug | Kucoin     | Socket 30 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:861 | Debug | Kucoin     | Socket 30 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:861 | Debug | Kucoin     | Socket 109 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:861 | Debug | Kucoin     | Socket 109 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:862 | Debug | Kucoin     | Socket 10 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:868 | Debug | Kucoin     | Socket 10 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:876 | Debug | Kucoin     | Socket 33 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:878 | Debug | Kucoin     | Socket 33 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:876 | Debug | Kucoin     | Socket 49 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:881 | Debug | Kucoin     | Socket 49 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:887 | Debug | Kucoin     | Socket 53 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:888 | Debug | Kucoin     | Socket 53 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:888 | Debug | Kucoin     | Socket 69 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:889 | Debug | Kucoin     | Socket 69 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:924 | Debug | Kucoin     | Socket 12 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:927 | Debug | Kucoin     | Socket 12 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:951 | Debug | Kucoin     | Socket 110 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:951 | Debug | Kucoin     | Socket 110 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:49:995 | Debug | Kucoin     | Socket 111 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:49:997 | Debug | Kucoin     | Socket 111 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:50:012 | Debug | Kucoin     | Socket 32 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:50:013 | Debug | Kucoin     | Socket 32 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:50:018 | Debug | Kucoin     | Socket 75 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:50:022 | Debug | Kucoin     | Socket 75 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:50:021 | Debug | Kucoin     | Socket 48 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

2022/07/06 16:30:50:023 | Debug | Kucoin     | Socket 48 failed to reconnect, will try again in 00:00:40
2022/07/06 16:30:50:024 | Debug | Kucoin     | Socket 95 connection failed: WebSocketException - The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at CryptoExchange.Net.Sockets.CryptoExchangeWebSocketClient.ConnectAsync()

**Comment by masherak** [comment]
Same problem for me

**Comment by JKorf** [comment]
See answer on #140. Closing this issue as it's the same
