### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by NinjaRaiden** [JKorf/Kucoin.Net#209]
Some functions like SpotApi.CommonSpotClient.GetBalancesAsync returns with this error message.

HttpRequestException - An error occurred while sending the request.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CryptoExchange.Net.Requests.Request.<GetResponseAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CryptoExchange.Net.RestApiClient.<GetResponseAsync>d__25`1.MoveNext()
  WebException - **The request was aborted: Could not create SSL/TLS secure channel.**
     at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

Tried with AutoTimestamp True and False. Same error.

**Comment by JKorf** [comment]
If you're running on an older operating system this might be the issue:
https://stackoverflow.com/a/2904963
